### ISSUE TITLE
Bug: Android - weird scrolling behaviour when focusing on an input box within a QDialog

### ISSUE THREAD

**Issue by nicholaszuccarelli** [pdanpdan/quasar#10] opened 2021-11-30 04:08 UTC
Android (both Browser and Cordova) has a weird scrolling bug where you can scroll the page while focussing on an input box. 
Could not replicate this problem on iOS. Problem also doesn't seem to exist on official Quasar v1.16

Videos below show it happening:

https://user-images.githubusercontent.com/13761766/143984143-fa30c024-eb4b-45b5-ba83-2b6495ad4ad6.mp4

https://user-images.githubusercontent.com/13761766/143984173-697ed9be-7c84-4307-bc41-9e575ff9550b.mp4

**Comment by pdanpdan** [comment] 2021-11-30 09:12
This behavior is intentional - it replicates the iOS one where the page does not shrink in height when keyboard is shown.
But it looks like on cordova I missed something and the dialog backdrop does not stretch fullscreen - I'll check it later.

**Comment by pdanpdan** [comment] 2021-11-30 18:38
I just tested on android (using capacitor, I cannot convince cordova to run) and all looks good.
Is it possible that in the second movie you are creating the grey backdrop yourself and it's not the backdrop from a dialog?

**Comment by nicholaszuccarelli** [comment] 2021-11-30 21:28
> Is it possible that in the second movie you are creating the grey backdrop yourself and it's not the backdrop from a dialog?

Nope. I'm just using Quasar's default QDialog to manage the backdrop. I didn't add the grey area.

**Comment by nicholaszuccarelli** [comment] 2021-12-01 00:41
https://github.com/nicholaszuccarelli/android-cordova-bugs-nov2021

Can be seen in this video when I scroll on the actual window rather than the dialog itself.

https://user-images.githubusercontent.com/13761766/144150875-4d94c27e-e2d7-4cfa-875a-4f2b736615a4.mp4

**Comment by pdanpdan** [comment] 2021-12-01 13:52
The menu not opening should be fixed in https://github.com/pdanpdan/quasar/releases/tag/quasar-pdan-v1.16.3-beta.3
The page that keeps the size when the keyboard is shown and a modal is on screen is by design to match iOS

**Closed as completed by pdanpdan** 2021-12-01 13:52 UTC
Labels: need more info
